name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest validators python-dateutil beautifulsoup4 black datefinder Markdown pandas pytest PyYAML PyGithub requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #- name: Set up log file
       # run: | 
        #  touch log.json
         #echo '# pipeline error log' >> log.md
          #echo '' >> log.md
         # echo '## Unaccessible Webpages' >> log.md
         # echo '' >> log.md
         # echo '|URL | Error Code | Error Reason|' >> log.md
         # echo '|--- | --- | ---|' >> log.md
        #working-directory: ${{env.odbodsPath}}
          
      - name: Run Script generate_new_mock_data.py
        run: python -m tests.generate_new_mock_data
        working-directory: ${{env.odbodsPath}}   
#       
#
      - name: Test with pytest
        run: |
          pytest
